name: orgfer_recommendation_system
description: Your description here
publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  iconly: ^1.0.1
  http: ^1.4.0
  badges: ^3.1.2
  google_fonts: ^6.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/